import createMiddleware from "next-intl/middleware";
import { NextResponse, type NextRequest } from "next/server";

import { routing } from "@/i18n/routing";
import { updateSession } from "@/lib/supabase/proxy";

const intlMiddleware = createMiddleware(routing);

export async function proxy(request: NextRequest) {
  const pathname = request.nextUrl.pathname;

  /*
   * These are global technical files.
   * They must never receive /en or /fr.
   */
  if (
    pathname === "/robots.txt" ||
    pathname === "/sitemap.xml" ||
    pathname === "/favicon.ico"
  ) {
    return NextResponse.next();
  }

  /*
   * Admin and API routes are not translated.
   * Supabase still protects and refreshes admin sessions.
   */
  if (
    pathname.startsWith("/admin") ||
    pathname.startsWith("/api")
  ) {
    return updateSession(request);
  }

  /*
   * Apply English/French routing to public website pages.
   */
  const intlResponse = intlMiddleware(request);

  /*
   * Preserve Supabase authentication cookies while using
   * the response generated by next-intl.
   */
  return updateSession(request, intlResponse);
}

export const config = {
  matcher: [
    "/((?!_next/static|_next/image|_next/data|favicon.ico|robots.txt|sitemap.xml|.*\\.(?:svg|png|jpg|jpeg|gif|webp|avif|ico|xml|txt)$).*)",
  ],
};